menu:
- {name: 'publications', url: '/publications'}
- {name: 'communications', url: '/communications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/martaxavier'}
- {icon: 'scholar', link: 'https://scholar.google.com/citations?user=ANUWCqMAAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/martalouresxavier'}

contacts:
- {name: 'Marta Xavier', title: 'PhD Candidate', department: 'LaSEEB-Institute for Systems and Robotics', institution: 'Instituto Superior Técnico, University of Lisbon', email: 'marta.xavier@tecnico.ulisboa.pt', image: 'assets/img/marta.jpg'}
